backend:
  name: git-gateway
  branch: next
media_folder: 'public/uploads'
public_folder: '/uploads'
collections:
  - label: 'Site Content'
    name: 'sitecontent'
    files:
      - label: 'Hero Section'
        name: 'hero'
        file: 'src/content/sitecontent/hero.md'
        fields:
          - { label: 'Site Heading', name: 'siteheading', widget: 'string' }
          - { label: 'Site Subheading', name: 'sitesubheading', widget: 'string' }
          - { label: 'Site Description', name: 'sitedescription', widget: 'text' }
          - {
              label: 'Site Logo',
              name: 'sitelogo',
              widget: 'image',
              default: 'uploads/c-flat-logo-basic-op-1-01.webp',
              required: false,
            }
          - { label: 'Hero Image', name: 'heroimage', widget: 'image', required: false }
          - { label: 'Background Image', name: 'bgimage', widget: 'image', required: false }
      - label: 'Officers Section'
        name: 'officerssection'
        file: 'src/content/sitecontent/officerssection.md'
        fields:
          - { label: 'Officers Heading', name: 'officersheading', widget: 'string' }
          - {
              label: 'Officers Subheading',
              name: 'officerssubheading',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Officers Description',
              name: 'officersdescription',
              widget: 'text',
              required: false,
            }
          - { label: 'Background Image', name: 'bgimage', widget: 'image', required: false }
      - label: 'Members Section'
        name: 'memberssection'
        file: 'src/content/sitecontent/memberssection.md'
        fields:
          - { label: 'Members Heading', name: 'membersheading', widget: 'string' }
          - {
              label: 'Members Subheading',
              name: 'memberssubheading',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Members Description',
              name: 'membersdescription',
              widget: 'text',
              required: false,
            }
          - { label: 'Background Image', name: 'bgimage', widget: 'image', required: false }
      - label: 'Concerts Section'
        name: 'concertssection'
        file: 'src/content/sitecontent/concertssection.md'
        fields:
          - { label: 'Concerts Heading', name: 'concertsheading', widget: 'string' }
          - {
              label: 'Concerts Subheading',
              name: 'concertssubheading',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Concerts Description',
              name: 'concertsdescription',
              widget: 'text',
              required: false,
            }
          - { label: 'Background Image', name: 'bgimage', widget: 'image', required: false }
      - label: 'Contact Section'
        name: 'contactsection'
        file: 'src/content/sitecontent/contactsection.md'
        fields:
          - { label: 'Contact Heading', name: 'contactheading', widget: 'string' }
          - {
              label: 'Contact Subheading',
              name: 'contactsubheading',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Contact Description',
              name: 'contactdescription',
              widget: 'text',
              required: false,
            }
          - { label: 'Background Image', name: 'bgimage', widget: 'image', required: false }
  - label: 'Members'
    name: 'members'
    folder: 'src/content/members'
    create: true
    sortable_fields: ['name', 'classof', 'voicepart', 'position', 'iscurrent']
    view_filters:
      - label: 'Current Members'
        field: 'iscurrent'
        pattern: 'true'
      - label: 'Past Members'
        field: 'iscurrent'
        pattern: 'false'
      - label: 'Officers'
        field: 'position'
        pattern: '(.|\s)*\S(.|\s)*'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Class Of', name: 'classof', widget: 'number' }
      - { label: 'Major', name: 'major', widget: 'number', required: false }
      - { label: 'Voice Part', name: 'voicepart', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string', required: false }
      - { label: 'Portrait', name: 'portrait', widget: 'image', required: false }
      - { label: 'Is Current', name: 'iscurrent', widget: 'boolean', default: true }
  - label: 'Concerts'
    name: 'concerts'
    folder: 'src/content/concerts'
    create: true
    sortable_fields: ['concertname', 'year']
    fields:
      - { label: 'Concert Name', name: 'concertname', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'number' }
      - {
          label: 'Semester',
          name: 'semester',
          widget: 'select',
          options: ['Spring', 'Fall'],
          default: '',
        }
      - label: 'Songs'
        name: 'songs'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'OPB', name: 'opb', widget: 'string' }
          - { label: 'Arranger', name: 'arranger', widget: 'string' }
          - { label: 'Soloist', name: 'soloist', widget: 'string', required: false }
          - {
              label: 'Vocal Percussion',
              name: 'vocalpercussion',
              widget: 'string',
              required: false,
            }
