backend:
  name: git-gateway
  branch: next
media_folder: 'public/uploads'
public_folder: '/uploads'
collections:
  - label: 'Members'
    name: 'members'
    folder: 'src/content/members'
    create: true
    sortable_fields: ['name', 'classof', 'voicepart', 'position', 'iscurrent']
    view_filters:
      - label: 'Current Members'
        field: 'iscurrent'
        pattern: 'true'
      - label: 'Past Members'
        field: 'iscurrent'
        pattern: 'false'
      - label: 'Officers'
        field: 'position'
        pattern: '(.|\s)*\S(.|\s)*'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', default: '' }
      - { label: 'Class Of', name: 'classof', widget: 'string', default: '' }
      - { label: 'Voice Part', name: 'voicepart', widget: 'string', default: '' }
      - { label: 'Position', name: 'position', widget: 'string', default: '', required: false }
      - { label: 'Is Current', name: 'iscurrent', widget: 'boolean', default: true }
